theme: user-guide
plugins:
  - $
  - script-style-optimizer
$legal:
  company: Xarial Pty Limited
  links:
    Terms Of Use: /terms-of-use
    Privacy: /privacy-policy
    Cookies: /cookies-policy
$google-analytics:
  traking-code: UA-160707877-2
$disqus:
  short-name: cad-plus
$cookie-consent:
  enable: true
  message: This website uses cookies to ensure you get the best experience on our website. By using our website you agree on the following <a href="/cookies-policy">Cookie Policy</a>, <a href="/privacy-policy">Privacy Policy</a>, and <a href="/terms-of-use">Terms Of Use</a>
$site-header:
  show_title: false
^tipue-search:
  page-content-node: //article
  search-page-layout: default
^script-style-optimizer:
  minify-css: true
  minify-js: true
  assets-scope-paths:
    - /assets/styles/*
    - /assets/scripts/*
  delete-unused-css: true
  delete-unused-js: true
  bundles:
    /assets/styles/main.min.css:
      - /assets/styles/social-share.css
      - /assets/styles/youtube.css
      - /assets/styles/base.css
      - /assets/styles/toc.css
      - /assets/styles/theme.css
      - /assets/styles/user-guide.css
      - /assets/styles/code-snippet.css
      - /assets/styles/responsive-image.css